server:
  port: 8088
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/mytest?useUnicode=true&characterEncoding=utf8
    username: root
    password: null
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
    cache: false
  redis:
    host: 127.0.0.1
    port: 6379
    timeout: 0
    password: root
mybatis:
  mapper-locations: classpath:com/sjtc/weiwen/*/mapper/*.xml, com/sjtc/weiwen/*/*/mapper/*.xml
  type-aliases-package: com.sjtc.weiweb.*.model
pagehelper:
  offset-as-page-num: true
  row-bounds-with-count: true
  reasonable: true
logging:
  level:
    com:
      looedu:
        mapper: debug